### PR TITLE
feat: Ankr Provider

### PR DESCRIPTION
**Pull request by codingwithmanny**
Added default support for ankr

BREAKING CHANGE: n

## Description

Added support ankr rpc provider

## Additional Information

- [x] I read the [contributing docs](/tmm/wagmi/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:

codingwithmanny.eth

### CODE REVIEW

**Comment by codingwithmanny** [comment]
@tmm for the tests failing, would you be able to give some guidance to get some of them passing or is this something that works and doesn't work from time to time?

**Review by jxom — APPROVED** [review]
Happy with this since Ankr is also supported by Ethers.

**Comment by tmm** [comment]
@codingwithmanny does Ankr support WebSockets? could be nice to add that in. Also, would be great to have a free premium account for wagmi so core team members can test.

**Comment by codingwithmanny** [comment]
@tmm I believe they do, I just need to double check.

Re: Premium account, I reached out to the team. I think something can be setup 😉

**Comment by tmm** [comment]
@codingwithmanny sg. let me know if you hear anything. once we get the key, we can test websocket support and get this out.

**Comment by tmm** [comment]
Closing this out until we get a key to test websocket support.

**Pull request closed without merging**
